# Generated by Django 3.2.12 on 2022-02-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upated at')),
                ('duty_post', models.CharField(choices=[('agent_1', 'Agent 1'), ('agent_2', 'Agent 2'), ('agent_3', 'Agent 3'), ('agent_4', 'Agent 4')], default='agent_1', max_length=50, verbose_name='Duty post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Agent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
