# Generated by Django 3.2.12 on 2022-02-16 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upated at')),
                ('amount_repaid', models.FloatField(verbose_name='Amount repaid')),
                ('loan_amount', models.FloatField(verbose_name='Loan amount')),
                ('arrears_prepayment', models.FloatField(verbose_name='Arrears prepayment')),
                ('expected_pay_date', models.DateField(verbose_name='Expected pay date')),
                ('coordinates', models.CharField(max_length=50, verbose_name='Coordinates')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
