# Generated by Django 3.2.12 on 2022-02-16 23:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='n/a', help_text="Phone number must be entered in the format: '+27815742271'. Up to 11 digits allowed.", max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\+?27?[6-8][0-9]{8}$'), 'Enter a valid phone number', 'Invalid phone number')], verbose_name='phone_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(db_index=True, default='n/a', help_text='Required. 255 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='Username'),
            preserve_default=False,
        ),
    ]
